### ISSUE TITLE
请问格式化用的什么插件？

### ISSUE THREAD

**Issue by xiaohuazi123** [may-fly/mayfly#25]
你这个格式化用的什么排版插件？
![QQ截图20220915123053](https://user-images.githubusercontent.com/45115671/190315064-e179bc7b-b364-497e-96be-4d496af41b7e.jpg)

**Comment by may-fly** [comment]
sql formatter

**Comment by xiaohuazi123** [comment]
请问是这个吗？
https://www.npmjs.com/package/sql-formatter

**Comment by may-fly** [comment]
是的

**Comment by xiaohuazi123** [comment]
好
